# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        tournois_result:
            properties:
                identifiant: ~
                buyin: { 'type': 'text',
                         'fielddata': true }
                prizepool: { 'type': 'text',
                             'fielddata': true }
                win: ~
                nbtour: ~
                ticket: ~
                money: ~
            persistence:
                driver: orm
                model: App\Entity\TournoiResult
            finder: ~
        tournois:
            properties:
                identifiant: { 'type': 'text',
                               'fielddata': true }
                buyin: { 'type': 'text',
                         'fielddata': true }
                prizepool: { 'type': 'text',
                             'fielddata': true }
                date: { 'type': 'date' }
                win: ~
                nbplayer: ~
                position: ~
                ticket: ~
                money: { 'type': 'text',
                         'fielddata': true }
            persistence:
                driver: orm
                model: App\Entity\Tournoi
            finder: ~
            settings:
                index:
                    max_result_window: 5000000

        plants:
            properties:
                seed.name: { 'type': 'text',
                             'fielddata': true }
                seed.duration: ~
                seed.quantity: ~
                qty: ~
                status: { 'type': 'text',
                          'fielddata': true }
                date_updated: ~
                comment: ~
            persistence:
                driver: orm
                model: App\Entity\Plant
            finder: ~
            settings:
                index:
                    max_result_window: 5000000

        seeds:
            properties:
                name: { 'type': 'keyword' }
                duration: ~
                quantity: ~
                commentaire: ~
            persistence:
                driver: orm
                model: App\Entity\Seed
            finder: ~
            settings:
                index:
                    max_result_window: 5000000

        cards:
            properties:
                value: { 'type': 'text',
                         'fielddata': true }
                color: { 'type': 'text',
                         'fielddata': true }
                count: { 'type': 'integer' }
                flop: { 'type': 'integer' }
                turn: { 'type': 'integer' }
                river: { 'type': 'integer' }
                mycard: { 'type': 'integer' }
                flopcard: { 'type': 'integer' }
                turncard: { 'type': 'integer' }
                rivercars: { 'type': 'integer' }
            persistence:
                driver: orm
                model: App\Entity\Cards
            finder: ~
            settings:
                index:
                    max_result_window: 5000000

        joueurs:
            properties:
                pseudo: { 'type': 'text',
                          'fielddata': true }
                hand_win: { 'type': 'integer' }
                tour_win: { 'type': 'integer' }
            persistence:
                driver: orm
                model: App\Entity\Joueur
            finder: ~
            settings:
                index:
                    max_result_window: 5000000

        mains:
            properties:
                tournoi: { 'type': 'text',
                           'fielddata': true }
                card1: { 'type': 'text' }
                card2: { 'type': 'text' }
                flop1: { 'type': 'text' }
                flop2: { 'type': 'text' }
                flop3: { 'type': 'text' }
                turn: { 'type': 'text' }
                river: { 'type': 'text' }
                player1: { 'type': 'text' }
                player2: { 'type': 'text' }
                player3: { 'type': 'text' }
                player4: { 'type': 'text' }
                player5: { 'type': 'text' }
                player6: { 'type': 'text' }
                player7: { 'type': 'text' }
                player8: { 'type': 'text' }
                player9: { 'type': 'text' }
                win: { 'type': 'boolean' }
            persistence:
                driver: orm
                model: App\Entity\Main
                model_to_elastica_transformer:
                    service: application_convert.index.mains

        mes_mains:
            properties:
                card1: { 'type': 'text' }
                card2: { 'type': 'text' }
                count: { 'type': 'integer'}
                win: { 'type': 'integer'}
            persistence:
                driver: orm
                model: App\Entity\MesMains
                model_to_elastica_transformer:
                    service: application_convert.index.mains

        paris:
            properties:
                date: { 'type': 'date' }
                win: { 'type': 'short'}
            persistence:
                driver: orm
                model: App\Entity\Paris
            settings:
                index:
                    max_result_window: 5000000

